### ISSUE TITLE
Mozart is not Baroque, 'Define Abstraction' section

### ISSUE THREAD

**Issue by Eisea904** [learn-co-curriculum/fewpjs-functions-in-javascript#6]
Hi in Recognizing JavaScript Events/Functions in JavaScript, under Define Abstractions it says “Mozart… does fit with ‘Baroque Masters’.”  Mozart was not Baroque, he was born and died in the Classical Period in 1756 - 1791.  The Baroque period ended between 1730 - 1750.  My guess is whoever wrote the lab has a CD titled “Baroque Masters” that has a Mozart piece on it.  Including him on these types of collection album helps it sell because his is one of the few names the general public recognizes and most listeners don’t know the difference.  J.S. Bach, Vivaldi, or Monteverdi's name can be used instead.
     -Alex Eisenhauer
          Former composition and orchestral conducting student
          Conservatory of Music at Brooklyn College (undergrad and started a Masters there)
          Mannes @ The New School (undergrad courses)

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved. Note, however, that if you are working in Canvas the changes may not show up right away.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
