### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by zkobrinsky** [learn-co-curriculum/fewpjs-functions-in-javascript#7]
"A function is an object that contains a sequence JavaScript statements." should be "A function is an object that contains a sequence of JavaScript statements."

It's missing "of."

**Comment by chihempat** [comment]
Can I work on this?

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved. Note, however, that if you are working in Canvas the changes may not show up right away.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
